[window]
dimensions = { columns = 140, lines = 40 }
opacity = 0.95

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "BoldItalic" }

[general]
# Color scheme
import = [ "./tokyo-night.toml" ]
